# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: rootpass
      POSTGRES_USER: root
      POSTGRES_DB: root
    ports:
      - 5432:5432
